package:
    name: peakachu
    version: "0.0.1"

source:
    path: ../

build:
    number: 1
    skip: True # [not py3k]

requirements:
    build:
        - python
        - setuptools
        - "biopython >=1.66"
        - "matplotlib >=1.5.1"
        - "pandas >=0.17.1"
        - "pysam >=0.9.0"
        - "numexpr >=2.5"
        - "bcbiogff >=0.6.2"
        - "statsmodels >=0.6.1"
        - "rpy2 >=2.7.6"
    run:
        - python
        - setuptools
        - "biopython >=1.66"
        - "matplotlib >=1.5.1"
        - "pandas >=0.17.1"
        - "pysam >=0.9.0"
        - "numexpr >=2.5"
        - "bcbiogff >=0.6.2"
        - "statsmodels >=0.6.1"
        - "rpy2 >=2.7.6"
        - bioconductor-deseq2
        - bioconductor-edger
        - blockbuster

test:
    imports:
        - peakachulib
    commands:
        - 'peakachu 2>&1 | grep "^usage" > /dev/null'
## the following requires tests, also the required files have to be made part of the distribution
#    commands:
#        - tests/test_all.py
